// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGTgnDB4O4AdMICtvQjMASR6Mb-RFfJA',
    appId: '1:818733020113:web:807b9107deb507ac26e6f0',
    messagingSenderId: '818733020113',
    projectId: 'blackjack-the-digital-realm',
    authDomain: 'blackjack-the-digital-realm.firebaseapp.com',
    storageBucket: 'blackjack-the-digital-realm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgGUDeG2tsVatktorxTnC-AgI3wGKmlw',
    appId: '1:818733020113:android:44beb30568ffc11526e6f0',
    messagingSenderId: '818733020113',
    projectId: 'blackjack-the-digital-realm',
    storageBucket: 'blackjack-the-digital-realm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOazwvotkQFO-48TZpstRU86ozdMdq-k',
    appId: '1:818733020113:ios:af051659158042e226e6f0',
    messagingSenderId: '818733020113',
    projectId: 'blackjack-the-digital-realm',
    storageBucket: 'blackjack-the-digital-realm.appspot.com',
    iosBundleId: 'com.example.blackjackTheDigitalRealm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOazwvotkQFO-48TZpstRU86ozdMdq-k',
    appId: '1:818733020113:ios:af051659158042e226e6f0',
    messagingSenderId: '818733020113',
    projectId: 'blackjack-the-digital-realm',
    storageBucket: 'blackjack-the-digital-realm.appspot.com',
    iosBundleId: 'com.example.blackjackTheDigitalRealm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGTgnDB4O4AdMICtvQjMASR6Mb-RFfJA',
    appId: '1:818733020113:web:4647e90b0ebb879726e6f0',
    messagingSenderId: '818733020113',
    projectId: 'blackjack-the-digital-realm',
    authDomain: 'blackjack-the-digital-realm.firebaseapp.com',
    storageBucket: 'blackjack-the-digital-realm.appspot.com',
  );
}
